# Generated by Django 5.2.3 on 2025-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_monthlybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
